//FILTER CATEGRIES
const categories=[
    {
        name:'All',
        filter:'all',
    },
    {
        name: 'Nature',
        filter:'nature',
    },
    {
        name:'Birds',
        filter:'birds',
    },
    {
        name:'Friends',
        filter:'friends',
    },
    {
        name:'Flower',
        filter:'flower',
    },
    ];
    const images =[
        {
            id:'1',
            url:'../pics/11.jpg',
            category:'birds',
            title:'11',
        },
        {
            id:'2',
            url:'../pics/12.jpg',
            category:'birds',
            title:'12',
        },
        {
            id:'3',
            url:'../pics/22.jpg',
            category:'birds',
            title:'22',
        },
        {
            id:'4',
            url:'../pics/ 13 copy.jpg',
            category:'friends',
            title:'13 copy',       
        },
        {
            id:'5',
            url:'../pics/14.jpg',
            category:'friends',
            title:'14',
        },
        {
            id:'6',
            url:'../pics/15.jpg',
            category:'friends',
            title:'15',
        },
        {
            id:'7',
            url:'../pics/16.jpg',
            category:'friends',
            title:'16',
        },
        {
            id:'8',
            url:'../pics/17.jpg',
            category:'friends',
            title:'17',
        },
        {
            id:'9',
            url:'../pics/18.jpg',
            category:'friends',
            title:'18',
        },
        {
            id:'10',
            url:'../pics/19.jpg',
            category:'friends',
            title:'19',
        },
        {
            id:'11',
            url:'../pics/20.jpg',
            category:'friends',
            title:'20',
        },
        {
            id:'12',
            url:'../pics/23.jpg',
            category:'River',
            title:'23',
        },
        {
            id:'13',
            url:'../pics/24.jpg',
            category:'river',
            title:'24',
        },
        {
            id:'14',
            url:'../pics/27.jpg',
            category:'river',
            title:'27',
        },
        {
            id:'15',
            url:'../pics/30.jpg',
            category:'river',
            title:'30',
        },
        {
            id:'16',
            url:'../pics/2.jpg',
            category:'nature',
            title:'2',
        },
        {
            id:'17',
            url:'../pics/2.jpg',
            category:'nature',
            title:'18',
        },
        {
            id:'18',
            url:'../pics/4.jpg',
            category:'nature',
            title:'4',
        },
        {
            id:'19',
            url:'../pics/9.jpg',
            category:'nature',
            title:'9',
        },
        {
            id:'20',
            url:'../pics/10.jpg',
            category:'nature',
            title:'10',
        },
        {
            id:'21',
            url:'../pics/21.jpg',
            category:'nature',
            title:'21',
        },
        {
            id:'22',
            url:'../pics/24.jpg',
            category:'nature',
            title:'24',
        },
        {
            id:'23',
            url:'../pics/23.jpg',
            category:'nature',
            title:'23',
        },
        {
            id:'24',
            url:'../pics/25.jpg',
            category:'nature',
            title:'25',
        },
        {
            id:'25',
            url:'../pics/26.jpg',
            category:'nature',
            title:'26',
        },
        {
            id:'26',
            url:'../pics/3.jpg',
            category:'flower',
            title:'3',
        },
        {
            id:'27',
            url:'../pics/6(2).jpg',
            category:'flower',
            title:'6(2)',
        },
        {
            id:'28',
            url:'../pics/7.jpg',
            category:'flower',
            title:'7',
        },
        {
            id:'29',
            url:'../pics/8.jpg',
            category:'flower',
            title:'8',
        },
    ];
        